version: '3.4'
services:
  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9091:8080
    links:
      - mongodb